/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * Event raise when a movement direction is detected in a ROI
 *
 * @event module:crowddetector#CrowdDetectorDirection
 *
 * @type {module:crowddetector#event:Media}
 *
 * @property {external:Number} directionAngle
 *  Direction angle of the detected movement in the ROI
 * @property {external:String} roiID
 *  Opaque String indicating the id of the involved ROI
 */

/**
 * Event raise when a level of fluidity is detected in a ROI
 *
 * @event module:crowddetector#CrowdDetectorFluidity
 *
 * @type {module:crowddetector#event:Media}
 *
 * @property {external:Number} fluidityPercentage
 *  Percentage of fluidity in the ROI
 * @property {external:Integer} fluidityLevel
 *  Level of fluidity in the ROI
 * @property {external:String} roiID
 *  Opaque String indicating the id of the involved ROI
 */

/**
 * Event raise when a level of occupancy is detected in a ROI
 *
 * @event module:crowddetector#CrowdDetectorOccupancy
 *
 * @type {module:crowddetector#event:Media}
 *
 * @property {external:Number} occupancyPercentage
 *  Percentage of occupancy in the ROI
 * @property {external:Integer} occupancyLevel
 *  Level of occupancy in the ROI
 * @property {external:String} roiID
 *  Opaque String indicating the id of the involved ROI
 */
