/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */


/**
 * Event raise when a movement direction is detected in a ROI
 *
 * @event module:crowddetector#CrowdDetectorDirection
 *
 * @type {module:crowddetector#event:Media}
 *
 * @property {external:Number} directionAngle
 *  Direction angle of the detected movement in the ROI
 * @property {external:String} roiID
 *  Opaque String indicating the id of the involved ROI
 */

/**
 * Event raise when a level of fluidity is detected in a ROI
 *
 * @event module:crowddetector#CrowdDetectorFluidity
 *
 * @type {module:crowddetector#event:Media}
 *
 * @property {external:Number} fluidityPercentage
 *  Percentage of fluidity in the ROI
 * @property {external:Integer} fluidityLevel
 *  Level of fluidity in the ROI
 * @property {external:String} roiID
 *  Opaque String indicating the id of the involved ROI
 */

/**
 * Event raise when a level of occupancy is detected in a ROI
 *
 * @event module:crowddetector#CrowdDetectorOccupancy
 *
 * @type {module:crowddetector#event:Media}
 *
 * @property {external:Number} occupancyPercentage
 *  Percentage of occupancy in the ROI
 * @property {external:Integer} occupancyLevel
 *  Level of occupancy in the ROI
 * @property {external:String} roiID
 *  Opaque String indicating the id of the involved ROI
 */
